### PR TITLE
BLM Tea time submission

### PR DESCRIPTION
**Pull request by markcmiller86**
* This is a **DRAFT** PR only
* Keep it around as a ref for next time.
* It has logic to auto-gen the white paper list
* There are notes there that explain how it works

### CODE REVIEW

**Comment by markcmiller86** [comment]
Oh, and you can see how it looks in [my fork](https://markcmiller86.github.io/CW20/WorkshopResources/WhitePapers/)

**Comment by markcmiller86** [comment]
@maherou here is my Tea time submission in **DRAFT** mode.

I am awaiting any inputs from @elaineraybourn and/or @curfman.

Also, PS, I goofed regarding the previous work I had done for you on auto-gening the white-paper list file using Liquid which was here in this PR. I still have it on a commit in my fork but lost it here (because I didn' know what I was doing) in trying to create this PR for this tea time submission.

**Comment by elaineraybourn** [comment]
I like your draft and provided my feedback in an email before I saw this issue. Thanks.

**Comment by markcmiller86** [comment]
Ok, thanks @elaineraybourn. Now, I am just going to sit tight and wait for @curfman who I think is very busy with SIAM this week.

**Comment by maherou** [comment]
@markcmiller86: I spoke with Lois today and we are both fine with the text as written.  Are you ready to submit it?  The intention is to combine this discussion with Mary Ann Leung's and have them both be part of the same Tea Time breakout session.

**Comment by markcmiller86** [comment]
@maherou and @curfman sure thing. For some reason, I had the impression I should wait for update/guidance from @curfman. Will submit now.

**Comment by markcmiller86** [comment]
Ok, its out of **DRAFT** mode and ready for you to merge.

**Comment by maherou** [comment]
Thank you.

**Pull request merged**
